In [10]:
import os, sys
from PIL import Image
import numpy as np

In [44]:
# specifying integer code of land cover classes
green = 1
water = 2
builtup = 3
barrenland = 4

# list of districts for which the accuracy is to be calculated
districts = ['Gurgaon','Hyderabad','Mumbai']

# Name of the main folder where the cropped tif files of predictions are stored
main_folder = 'Classification_Accuracy_Test'


In [60]:
'''
This function is used to calculate the precision of each landcover class from confusion matrix
'''
def precision(label, confusion_matrix):
    col = confusion_matrix[:, label]
    return confusion_matrix[label, label] / col.sum()
   
'''
This function is used to calculate the recall value of each landcover class from confusion matrix
'''
def recall(label, confusion_matrix):
    row = confusion_matrix[label, :]
    return confusion_matrix[label, label] / row.sum()

'''
This function is used to calculate the overall accuracy of land cover classification in a district
'''
def accuracy(confusion_matrix):
    diagonal_sum = confusion_matrix.trace()
    sum_of_all_elements = confusion_matrix.sum()
    return diagonal_sum / sum_of_all_elements 



In [67]:
landcover_classes = ['Green','Water','Builtup','Barrenland']
for district in districts:
    confusion_matrix = [] # this is the confusion matrix against each district

    for landcover in landcover_classes:
        landcover_predicted_class_count = [0, 0, 0, 0] # this list stores the count of a particular class predicted as other classes 
        tif_files_path = main_folder+'/'+district+'/'+landcover        
        
        for tif_file in os.listdir(tif_files_path):
            tif_image = np.asarray(Image.open(tif_files_path+'/'+tif_file))
            
            if green in np.unique(tif_image, return_counts=True)[0]:
                landcover_predicted_class_count[0] += np.unique(tif_image, return_counts=True)[1][np.where(np.unique(tif_image,return_counts=True)[0]==green)[0][0]]
            
            if water in np.unique(tif_image, return_counts=True)[0]:
                landcover_predicted_class_count[1] += np.unique(tif_image, return_counts=True)[1][np.where(np.unique(tif_image,return_counts=True)[0]==water)[0][0]]
                
            if builtup in np.unique(tif_image, return_counts=True)[0]:
                landcover_predicted_class_count[2] += np.unique(tif_image, return_counts=True)[1][np.where(np.unique(tif_image,return_counts=True)[0]==builtup)[0][0]]
                
            if barrenland in np.unique(tif_image, return_counts=True)[0]:
                landcover_predicted_class_count[3] += np.unique(tif_image, return_counts=True)[1][np.where(np.unique(tif_image,return_counts=True)[0]==barrenland)[0][0]]
                
        confusion_matrix.append(landcover_predicted_class_count)
    
    confusion_matrix = np.array(confusion_matrix)
    print("Confusion Matrix for district ",district,"is: \n",confusion_matrix,"\n")
    
    print("Accuracy: ",accuracy(confusion_matrix),"\n")
    print("label precision recall")
    for label in range(4):
        print(f"{label:5d} {precision(label, confusion_matrix):9.3f} {recall(label, confusion_matrix):6.3f}")
    print("\n\n")
            

Confusion Matrix for district  Gurgaon is: 
 [[4967    0    0   22]
 [  62  635    3    0]
 [   2    0 1246    1]
 [ 803    0  274  621]] 

Accuracy:  0.8648679944418712 

label precision recall
    0     0.851  0.996
    1     1.000  0.907
    2     0.818  0.998
    3     0.964  0.366



Confusion Matrix for district  Hyderabad is: 
 [[ 800    3    1    0]
 [   0 1426    0    0]
 [   2    0 2207    0]
 [   3    0   14   16]] 

Accuracy:  0.9948568872987478 

label precision recall
    0     0.994  0.995
    1     0.998  1.000
    2     0.993  0.999
    3     1.000  0.485



Confusion Matrix for district  Mumbai is: 
 [[ 366    0    0    0]
 [   0 2862    0    0]
 [  15   32 2351    0]
 [  17    0  111  266]] 

Accuracy:  0.9709302325581395 

label precision recall
    0     0.920  1.000
    1     0.989  1.000
    2     0.955  0.980
    3     1.000  0.675



